#include "pacman.h"

// initial states
state_t state = STATE_RESET;
game_t game;

//TODO: VER_WALLs
const cell_t initial_grid[GRID_HEIGHT][GRID_WIDTH] = {
		{VER_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL}, 
		{HOR_WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, HOR_WALL, HOR_WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, HOR_WALL},
		{HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL},
		{HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL},
		{HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL},
		{HOR_WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, HOR_WALL},
		{HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL},
		{HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL},
		{HOR_WALL, PILL, PILL, PILL, PILL, PILL, PILL, HOR_WALL, HOR_WALL, PILL, PILL, PILL, PILL, HOR_WALL, HOR_WALL, PILL, PILL, PILL, PILL, HOR_WALL, HOR_WALL, PILL, PILL, PILL, PILL, PILL, PILL, HOR_WALL},
		{HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL},
		{HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL},
		{HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL},
		{HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, HOR_WALL, EMPTY, EMPTY, HOR_WALL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL},
		{HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL},
		{EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, PILL, EMPTY, EMPTY, EMPTY, HOR_WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, HOR_WALL, EMPTY, EMPTY, EMPTY, PILL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY},
		{HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL}, 
		{HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL},
		{HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL},
		{HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL},
		{HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, EMPTY, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL},
		{HOR_WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, HOR_WALL, HOR_WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, HOR_WALL},
		{HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL},
		{HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL},
		{HOR_WALL, PILL, PILL, PILL, HOR_WALL, HOR_WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, HOR_WALL, HOR_WALL, PILL, PILL, PILL, HOR_WALL},
		{HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL},
		{HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL},
		{HOR_WALL, PILL, PILL, PILL, PILL, PILL, PILL, HOR_WALL, HOR_WALL, PILL, PILL, PILL, PILL, HOR_WALL, HOR_WALL, PILL, PILL, PILL, PILL, HOR_WALL, HOR_WALL, PILL, PILL, PILL, PILL, PILL, PILL, HOR_WALL},
		{HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL},
		{HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, PILL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, PILL, HOR_WALL},
		{HOR_WALL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, PILL, HOR_WALL},
		{HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL, HOR_WALL}
};	

cell_t grid[GRID_HEIGHT][GRID_WIDTH];

void pacman(void){
	
	while (1) {
		switch(state){
			case STATE_RESET:
				// copy const matrix to play again from initial state
				memcpy((void*)grid, (void*)initial_grid, GRID_HEIGHT*GRID_WIDTH*sizeof(cell_t));
				init_game(&game);
				wait_ready();
				state = STATE_READY;
				break;
			case STATE_READY:
				draw_game(grid,&game);
				state = STATE_PLAY;
				break;
			case STATE_PLAY:
				state = !!(play_game(grid,&game)) ? STATE_WIN : STATE_LOOSE;
				break;
			case STATE_WIN:
				win(grid, &game);
				state = STATE_RESET;
				break;
			case STATE_LOOSE:
				loose(grid, &game);
				state = STATE_RESET;
				break;
		}
	}
}